try:
    raise Exception("Mayhem!!!")
except Exception as e:
    print("Error was: ", e)